//
// File generated by rootcint at Sun Jan 18 22:01:20 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME sidviewDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "sidviewDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void sidView_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_sidView(void *p);
   static void deleteArray_sidView(void *p);
   static void destruct_sidView(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::sidView*)
   {
      ::sidView *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::sidView >(0);
      static ::ROOT::TGenericClassInfo 
         instance("sidView", ::sidView::Class_Version(), "./sidview.h", 44,
                  typeid(::sidView), DefineBehavior(ptr, ptr),
                  &::sidView::Dictionary, isa_proxy, 4,
                  sizeof(::sidView) );
      instance.SetDelete(&delete_sidView);
      instance.SetDeleteArray(&deleteArray_sidView);
      instance.SetDestructor(&destruct_sidView);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::sidView*)
   {
      return GenerateInitInstanceLocal((::sidView*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::sidView*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *sidView::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *sidView::Class_Name()
{
   return "sidView";
}

//______________________________________________________________________________
const char *sidView::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::sidView*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int sidView::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::sidView*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void sidView::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::sidView*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *sidView::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::sidView*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void sidView::Streamer(TBuffer &R__b)
{
   // Stream an object of class sidView.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(sidView::Class(),this);
   } else {
      R__b.WriteClassBuffer(sidView::Class(),this);
   }
}

//______________________________________________________________________________
void sidView::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class sidView.
      TClass *R__cl = ::sidView::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEc", &fEc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fButtonExit", &fButtonExit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMenuBar", &fMenuBar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMenuFile", &fMenuFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMenuUpdate", &fMenuUpdate);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMenuHelp", &fMenuHelp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCanvas", &fCanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fListTree", &fListTree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fBaseLTI", &fBaseLTI);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fStatus", &fStatus);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fGraph", &fGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHist1D", &fHist1D);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHist2D", &fHist2D);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hWire[100]", &hWire);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "iTH1", &iTH1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ss", &ss);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*s0", &s0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mess", &mess);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*s", &s);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mon", &mon);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*threadServer", &threadServer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "serv", &serv);
      R__insp.InspectMember(serv, "serv.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*timer", &timer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ServerConn", &ServerConn);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "serverConnected", &serverConnected);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "strHist[50]", strHist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "str[64]", str);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pic", &pic);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*item", &item);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_sidView(void *p) {
      delete ((::sidView*)p);
   }
   static void deleteArray_sidView(void *p) {
      delete [] ((::sidView*)p);
   }
   static void destruct_sidView(void *p) {
      typedef ::sidView current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::sidView

/********************************************************
* sidviewDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablesidviewDict();

extern "C" void G__set_cpp_environmentsidviewDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("sidview.h");
  G__cpp_reset_tagtablesidviewDict();
}
#include <new>
extern "C" int G__cpp_dllrevsidviewDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* sidView */
static int G__sidviewDict_827_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   sidView* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new sidView(
(TGWindow*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) sidView(
(TGWindow*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__sidviewDictLN_sidView));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) sidView::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) sidView::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) sidView::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      sidView::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sidView*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) sidView::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) sidView::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) sidView::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) sidView::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sidView*) G__getstructoffset())->DoCloseWindow();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sidView*) G__getstructoffset())->HandleMenu((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((sidView*) G__getstructoffset())->GetObject((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sidView*) G__getstructoffset())->DataDropped((TGListTreeItem*) G__int(libp->para[0]), (TDNDData*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sidView*) G__getstructoffset())->ResetStatus();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sidView*) G__getstructoffset())->addHist();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sidView*) G__getstructoffset())->openServer();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sidView*) G__getstructoffset())->Update();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sidView*) G__getstructoffset())->RefreshCanvasInf();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sidView*) G__getstructoffset())->slotRegister();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sidviewDict_827_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sidView*) G__getstructoffset())->slotSetCanData();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef sidView G__TsidView;
static int G__sidviewDict_827_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (sidView*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((sidView*) (soff+(sizeof(sidView)*i)))->~G__TsidView();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (sidView*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((sidView*) (soff))->~G__TsidView();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* sidView */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncsidviewDict {
 public:
  G__Sizep2memfuncsidviewDict(): p(&G__Sizep2memfuncsidviewDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncsidviewDict::*p)();
};

size_t G__get_sizep2memfuncsidviewDict()
{
  G__Sizep2memfuncsidviewDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancesidviewDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__sidviewDictLN_sidView))) {
     sidView *G__Lderived;
     G__Lderived=(sidView*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__sidviewDictLN_sidView),G__get_linked_tagnum(&G__sidviewDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__sidviewDictLN_sidView),G__get_linked_tagnum(&G__sidviewDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__sidviewDictLN_sidView),G__get_linked_tagnum(&G__sidviewDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__sidviewDictLN_sidView),G__get_linked_tagnum(&G__sidviewDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__sidviewDictLN_sidView),G__get_linked_tagnum(&G__sidviewDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__sidviewDictLN_sidView),G__get_linked_tagnum(&G__sidviewDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__sidviewDictLN_sidView),G__get_linked_tagnum(&G__sidviewDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablesidviewDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__sidviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sidviewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sidviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sidviewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sidviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__sidviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sidviewDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sidviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sidviewDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sidviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__sidviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__sidviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__sidviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__sidviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__sidviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__sidviewDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__sidviewDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sidviewDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sidviewDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sidviewDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sidviewDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__sidviewDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__sidviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__sidviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sidviewDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sidviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sidviewDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sidviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__sidviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__sidviewDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__sidviewDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__sidviewDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__sidviewDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__sidviewDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sidviewDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sidviewDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sidviewDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sidviewDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__sidviewDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__sidviewDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__sidviewDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__sidviewDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* sidView */
static void G__setup_memvarsidView(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__sidviewDictLN_sidView));
   { sidView *p; p=(sidView*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TRootEmbeddedCanvas),-1,-1,2,"fEc=",0,"embedded canvas");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TGTextButton),-1,-1,2,"fButtonExit=",0,"\"Exit\" text button");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TGMenuBar),-1,-1,2,"fMenuBar=",0,"main menu bar");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TGPopupMenu),-1,-1,2,"fMenuFile=",0,"\"File\" popup menu entry");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TGPopupMenu),-1,-1,2,"fMenuUpdate=",0,"\"Help\" popup menu entry");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TGPopupMenu),-1,-1,2,"fMenuHelp=",0,"\"Help\" popup menu entry");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TCanvas),-1,-1,2,"fCanvas=",0,"canvas");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TGListTree),-1,-1,2,"fListTree=",0,"left list tree");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TGListTreeItem),-1,-1,2,"fBaseLTI=",0,"base (root) list tree item");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TGLabel),-1,-1,2,"fStatus=",0,"label used to display status");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TGraph),-1,-1,2,"fGraph=",0,"TGraph object");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TH1F),-1,-1,2,"fHist1D=",0,"1D histogram");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TH2F),-1,-1,2,"fHist2D=",0,"2D histogram");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TH1F),-1,-1,2,"hWire[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"iTH1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TServerSocket),-1,-1,2,"ss=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TSocket),-1,-1,2,"s0=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TMessage),-1,-1,2,"mess=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TSocket),-1,-1,2,"s=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TMonitor),-1,-1,2,"mon=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TThread),-1,-1,2,"threadServer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__sidviewDictLN_viewServer),-1,-1,2,"serv=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TTimer),-1,-1,2,"timer=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"ServerConn=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"serverConnected=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TString),-1,-1,2,"strHist[50]=",0,(char*)NULL);
   G__memvar_setup((void*)0,99,0,0,-1,-1,-1,2,"str[64]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pic)-(long)(p)),85,0,1,G__get_linked_tagnum(&G__sidviewDictLN_TGPicture),-1,-1,1,"pic=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->item)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__sidviewDictLN_TGListTreeItem),-1,-1,1,"item=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarsidviewDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncsidView(void) {
   /* sidView */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__sidviewDictLN_sidView));
   G__memfunc_setup("sidView",731,G__sidviewDict_827_0_1, 105, G__get_linked_tagnum(&G__sidviewDictLN_sidView), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p i - - 0 - w "
"i - - 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__sidviewDict_827_0_2, 85, G__get_linked_tagnum(&G__sidviewDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&sidView::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__sidviewDict_827_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&sidView::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__sidviewDict_827_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&sidView::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__sidviewDict_827_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&sidView::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__sidviewDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__sidviewDict_827_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__sidviewDict_827_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&sidView::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__sidviewDict_827_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&sidView::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__sidviewDict_827_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&sidView::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__sidviewDict_827_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&sidView::DeclFileLine) ), 0);
   G__memfunc_setup("DoCloseWindow",1313,G__sidviewDict_827_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleMenu",993,G__sidviewDict_827_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetObject",887,G__sidviewDict_827_0_16, 85, G__get_linked_tagnum(&G__sidviewDictLN_TObject), -1, 0, 1, 1, 1, 0, "C - - 10 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DataDropped",1096,G__sidviewDict_827_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TGListTreeItem' - 0 - item U 'TDNDData' - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ResetStatus",1159,G__sidviewDict_827_0_18, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addHist",705,G__sidviewDict_827_0_19, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("openServer",1065,G__sidviewDict_827_0_20, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Update",611,G__sidviewDict_827_0_21, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RefreshCanvasInf",1608,G__sidviewDict_827_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("slotRegister",1287,G__sidviewDict_827_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("slotSetCanData",1402,G__sidviewDict_827_0_24, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~sidView", 857, G__sidviewDict_827_0_25, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncsidviewDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {
}

static void G__cpp_setup_global10() {
}

static void G__cpp_setup_global11() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalsidviewDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
  G__cpp_setup_global10();
  G__cpp_setup_global11();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcsidviewDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__sidviewDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TTimer = { "TTimer" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__sidviewDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TSocket = { "TSocket" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TServerSocket = { "TServerSocket" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGPicture = { "TGPicture" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__sidviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TDNDData = { "TDNDData" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGPopupMenu = { "TGPopupMenu" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGMenuBar = { "TGMenuBar" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TThread = { "TThread" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGListTreeItem = { "TGListTreeItem" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TGListTree = { "TGListTree" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TMessage = { "TMessage" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_TMonitor = { "TMonitor" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_viewServer = { "viewServer" , 99 , -1 };
G__linked_taginfo G__sidviewDictLN_sidView = { "sidView" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablesidviewDict() {
  G__sidviewDictLN_TClass.tagnum = -1 ;
  G__sidviewDictLN_TBuffer.tagnum = -1 ;
  G__sidviewDictLN_TMemberInspector.tagnum = -1 ;
  G__sidviewDictLN_TObject.tagnum = -1 ;
  G__sidviewDictLN_TString.tagnum = -1 ;
  G__sidviewDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__sidviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__sidviewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sidviewDictLN_TTimer.tagnum = -1 ;
  G__sidviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__sidviewDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sidviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__sidviewDictLN_TCanvas.tagnum = -1 ;
  G__sidviewDictLN_TQObject.tagnum = -1 ;
  G__sidviewDictLN_TSocket.tagnum = -1 ;
  G__sidviewDictLN_TServerSocket.tagnum = -1 ;
  G__sidviewDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__sidviewDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sidviewDictLN_TGObject.tagnum = -1 ;
  G__sidviewDictLN_TGWindow.tagnum = -1 ;
  G__sidviewDictLN_TGPicture.tagnum = -1 ;
  G__sidviewDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__sidviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__sidviewDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sidviewDictLN_TGFrame.tagnum = -1 ;
  G__sidviewDictLN_TGCompositeFrame.tagnum = -1 ;
  G__sidviewDictLN_TGTextButton.tagnum = -1 ;
  G__sidviewDictLN_TDNDData.tagnum = -1 ;
  G__sidviewDictLN_TGMainFrame.tagnum = -1 ;
  G__sidviewDictLN_TGPopupMenu.tagnum = -1 ;
  G__sidviewDictLN_TGLabel.tagnum = -1 ;
  G__sidviewDictLN_TGMenuBar.tagnum = -1 ;
  G__sidviewDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__sidviewDictLN_TH1F.tagnum = -1 ;
  G__sidviewDictLN_TThread.tagnum = -1 ;
  G__sidviewDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__sidviewDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__sidviewDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__sidviewDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__sidviewDictLN_TH2F.tagnum = -1 ;
  G__sidviewDictLN_TGraph.tagnum = -1 ;
  G__sidviewDictLN_TGListTreeItem.tagnum = -1 ;
  G__sidviewDictLN_TGListTree.tagnum = -1 ;
  G__sidviewDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__sidviewDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sidviewDictLN_TMessage.tagnum = -1 ;
  G__sidviewDictLN_TMonitor.tagnum = -1 ;
  G__sidviewDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__sidviewDictLN_viewServer.tagnum = -1 ;
  G__sidviewDictLN_sidView.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablesidviewDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TString);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TTimer);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TSocket);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TServerSocket);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGPicture);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TDNDData);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGPopupMenu);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGLabel);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGMenuBar);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TH1F);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TThread);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TH2F);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGraph);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGListTreeItem);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TGListTree);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TMessage);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_TMonitor);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__sidviewDictLN_viewServer);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__sidviewDictLN_sidView),sizeof(sidView),-1,324608,(char*)NULL,G__setup_memvarsidView,G__setup_memfuncsidView);
}
extern "C" void G__cpp_setupsidviewDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupsidviewDict()");
  G__set_cpp_environmentsidviewDict();
  G__cpp_setup_tagtablesidviewDict();

  G__cpp_setup_inheritancesidviewDict();

  G__cpp_setup_typetablesidviewDict();

  G__cpp_setup_memvarsidviewDict();

  G__cpp_setup_memfuncsidviewDict();
  G__cpp_setup_globalsidviewDict();
  G__cpp_setup_funcsidviewDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncsidviewDict();
  return;
}
class G__cpp_setup_initsidviewDict {
  public:
    G__cpp_setup_initsidviewDict() { G__add_setup_func("sidviewDict",(G__incsetup)(&G__cpp_setupsidviewDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initsidviewDict() { G__remove_setup_func("sidviewDict"); }
};
G__cpp_setup_initsidviewDict G__cpp_setup_initializersidviewDict;

