/********************************************************************
* viewserverDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error viewserverDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableviewserverDict();
extern void G__cpp_setup_inheritanceviewserverDict();
extern void G__cpp_setup_typetableviewserverDict();
extern void G__cpp_setup_memvarviewserverDict();
extern void G__cpp_setup_globalviewserverDict();
extern void G__cpp_setup_memfuncviewserverDict();
extern void G__cpp_setup_funcviewserverDict();
extern void G__set_cpp_environmentviewserverDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "viewserver.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__viewserverDictLN_TClass;
extern G__linked_taginfo G__viewserverDictLN_TBuffer;
extern G__linked_taginfo G__viewserverDictLN_TMemberInspector;
extern G__linked_taginfo G__viewserverDictLN_TString;
extern G__linked_taginfo G__viewserverDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__viewserverDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__viewserverDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__viewserverDictLN_TList;
extern G__linked_taginfo G__viewserverDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__viewserverDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__viewserverDictLN_TSocket;
extern G__linked_taginfo G__viewserverDictLN_TServerSocket;
extern G__linked_taginfo G__viewserverDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__viewserverDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__viewserverDictLN_TMessage;
extern G__linked_taginfo G__viewserverDictLN_TThread;
extern G__linked_taginfo G__viewserverDictLN_TQObject;
extern G__linked_taginfo G__viewserverDictLN_TQObjSender;
extern G__linked_taginfo G__viewserverDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__viewserverDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__viewserverDictLN_TMonitor;
extern G__linked_taginfo G__viewserverDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__viewserverDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__viewserverDictLN_TH1;
extern G__linked_taginfo G__viewserverDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__viewserverDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__viewserverDictLN_TH2;
extern G__linked_taginfo G__viewserverDictLN_TH3;
extern G__linked_taginfo G__viewserverDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__viewserverDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__viewserverDictLN_TSQLStatement;
extern G__linked_taginfo G__viewserverDictLN_TSQLServer;
extern G__linked_taginfo G__viewserverDictLN_viewServer;

/* STUB derived class for protected member access */
