//
// File generated by rootcint at Sun Jan 18 22:01:01 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME viewserverDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "viewserverDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void viewServer_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_viewServer(void *p = 0);
   static void *newArray_viewServer(Long_t size, void *p);
   static void delete_viewServer(void *p);
   static void deleteArray_viewServer(void *p);
   static void destruct_viewServer(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::viewServer*)
   {
      ::viewServer *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::viewServer >(0);
      static ::ROOT::TGenericClassInfo 
         instance("viewServer", ::viewServer::Class_Version(), "./viewserver.h", 37,
                  typeid(::viewServer), DefineBehavior(ptr, ptr),
                  &::viewServer::Dictionary, isa_proxy, 4,
                  sizeof(::viewServer) );
      instance.SetNew(&new_viewServer);
      instance.SetNewArray(&newArray_viewServer);
      instance.SetDelete(&delete_viewServer);
      instance.SetDeleteArray(&deleteArray_viewServer);
      instance.SetDestructor(&destruct_viewServer);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::viewServer*)
   {
      return GenerateInitInstanceLocal((::viewServer*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::viewServer*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *viewServer::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *viewServer::Class_Name()
{
   return "viewServer";
}

//______________________________________________________________________________
const char *viewServer::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::viewServer*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int viewServer::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::viewServer*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void viewServer::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::viewServer*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *viewServer::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::viewServer*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void viewServer::Streamer(TBuffer &R__b)
{
   // Stream an object of class viewServer.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(viewServer::Class(),this);
   } else {
      R__b.WriteClassBuffer(viewServer::Class(),this);
   }
}

//______________________________________________________________________________
void viewServer::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class viewServer.
      TClass *R__cl = ::viewServer::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fQObject", &fQObject);
      R__insp.InspectMember(fQObject, "fQObject.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "serverConnected", &serverConnected);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "stopThread", &stopThread);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ss", &ss);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*s0", &s0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mess", &mess);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*s", &s);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mon", &mon);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*threadServer", &threadServer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*threadUpdate", &threadUpdate);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "str[64]", str);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h1Hist[100]", &h1Hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h2Hist[100]", &h2Hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h3Hist[100]", &h3Hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "iTH1", &iTH1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "iTH2", &iTH2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "iTH3", &iTH3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*dbSQL", &dbSQL);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*stmtSQL", &stmtSQL);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "strCanPrimitive[200]", strCanPrimitive);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "strHistName[200]", strHistName);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "numPadCan", &numPadCan);
      TQObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_viewServer(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::viewServer : new ::viewServer;
   }
   static void *newArray_viewServer(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::viewServer[nElements] : new ::viewServer[nElements];
   }
   // Wrapper around operator delete
   static void delete_viewServer(void *p) {
      delete ((::viewServer*)p);
   }
   static void deleteArray_viewServer(void *p) {
      delete [] ((::viewServer*)p);
   }
   static void destruct_viewServer(void *p) {
      typedef ::viewServer current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::viewServer

/********************************************************
* viewserverDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableviewserverDict();

extern "C" void G__set_cpp_environmentviewserverDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("viewserver.h");
  G__cpp_reset_tagtableviewserverDict();
}
#include <new>
extern "C" int G__cpp_dllrevviewserverDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* viewServer */
static int G__viewserverDict_602_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const viewServer*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((viewServer*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((viewServer*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((viewServer*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((viewServer*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((viewServer*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   G__va_arg_buf G__va_arg_bufobj;
   G__va_arg_put(&G__va_arg_bufobj, libp, 2);
      ((viewServer*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), G__va_arg_bufobj);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   viewServer* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new viewServer[n];
     } else {
       p = new((void*) gvp) viewServer[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new viewServer;
     } else {
       p = new((void*) gvp) viewServer;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__viewserverDictLN_viewServer));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      viewServer::ConnectServerThread((void*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      viewServer::UpdateServerThread((void*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->ConnectServer();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->UpdateServer();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->startConnectServerThread();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->startUpdateServerThread();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->stopServerThread();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->sigFinishedReg();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->sigSetCanData();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) viewServer::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) viewServer::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) viewServer::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      viewServer::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((viewServer*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) viewServer::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) viewServer::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) viewServer::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__viewserverDict_602_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) viewServer::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef viewServer G__TviewServer;
static int G__viewserverDict_602_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (viewServer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((viewServer*) (soff+(sizeof(viewServer)*i)))->~G__TviewServer();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (viewServer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((viewServer*) (soff))->~G__TviewServer();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* viewServer */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncviewserverDict {
 public:
  G__Sizep2memfuncviewserverDict(): p(&G__Sizep2memfuncviewserverDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncviewserverDict::*p)();
};

size_t G__get_sizep2memfuncviewserverDict()
{
  G__Sizep2memfuncviewserverDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceviewserverDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__viewserverDictLN_viewServer))) {
     viewServer *G__Lderived;
     G__Lderived=(viewServer*)0x1000;
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__viewserverDictLN_viewServer),G__get_linked_tagnum(&G__viewserverDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableviewserverDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 4 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__viewserverDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__viewserverDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__viewserverDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__viewserverDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__viewserverDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__viewserverDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__viewserverDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__viewserverDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__viewserverDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__viewserverDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__viewserverDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__viewserverDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__viewserverDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__viewserverDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__viewserverDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__viewserverDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__viewserverDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__viewserverDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__viewserverDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__viewserverDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__viewserverDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__viewserverDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__viewserverDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__viewserverDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__viewserverDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__viewserverDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__viewserverDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__viewserverDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__viewserverDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__viewserverDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__viewserverDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__viewserverDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__viewserverDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__viewserverDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* viewServer */
static void G__setup_memvarviewServer(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__viewserverDictLN_viewServer));
   { viewServer *p; p=(viewServer*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->serverConnected)-(long)(p)),103,0,0,-1,-1,-1,1,"serverConnected=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->stopThread)-(long)(p)),103,0,0,-1,-1,-1,1,"stopThread=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ss)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TServerSocket),-1,-1,1,"ss=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->s0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TSocket),-1,-1,1,"s0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mess)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TMessage),-1,-1,1,"mess=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->s)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TSocket),-1,-1,1,"s=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mon)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TMonitor),-1,-1,1,"mon=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->threadServer)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TThread),-1,-1,1,"threadServer=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->threadUpdate)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TThread),-1,-1,1,"threadUpdate=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->str)-(long)(p)),99,0,0,-1,-1,-1,1,"str[64]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->h1Hist)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TH1),-1,-1,1,"h1Hist[100]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->h2Hist)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TH2),-1,-1,1,"h2Hist[100]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->h3Hist)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TH3),-1,-1,1,"h3Hist[100]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iTH1)-(long)(p)),105,0,0,-1,-1,-1,1,"iTH1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iTH2)-(long)(p)),105,0,0,-1,-1,-1,1,"iTH2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iTH3)-(long)(p)),105,0,0,-1,-1,-1,1,"iTH3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dbSQL)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TSQLServer),-1,-1,1,"dbSQL=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->stmtSQL)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TSQLStatement),-1,-1,1,"stmtSQL=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->strCanPrimitive)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TString),-1,-1,1,"strCanPrimitive[200]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->strHistName)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TString),-1,-1,1,"strHistName[200]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->numPadCan)-(long)(p)),105,0,0,-1,-1,-1,1,"numPadCan=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__viewserverDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarviewserverDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncviewServer(void) {
   /* viewServer */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__viewserverDictLN_viewServer));
   G__memfunc_setup("GetListOfSignals",1602,G__viewserverDict_602_0_1, 85, G__get_linked_tagnum(&G__viewserverDictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__viewserverDict_602_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__viewserverDict_602_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LowPriority",1172,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("EmitVA",550,G__viewserverDict_602_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__viewserverDict_602_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ChangedBy",869,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Message",709,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("viewServer",1074,G__viewserverDict_602_0_26, 105, G__get_linked_tagnum(&G__viewserverDictLN_viewServer), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ConnectServerThread",1945,G__viewserverDict_602_0_27, 121, -1, -1, 0, 1, 3, 1, 0, "Y - - 0 - arg", (char*)NULL, (void*) G__func2void( (void (*)(void*))(&viewServer::ConnectServerThread) ), 0);
   G__memfunc_setup("UpdateServerThread",1842,G__viewserverDict_602_0_28, 121, -1, -1, 0, 1, 3, 1, 0, "Y - - 0 - arg", (char*)NULL, (void*) G__func2void( (void (*)(void*))(&viewServer::UpdateServerThread) ), 0);
   G__memfunc_setup("ConnectServer",1345,G__viewserverDict_602_0_29, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("UpdateServer",1242,G__viewserverDict_602_0_30, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("startConnectServerThread",2503,G__viewserverDict_602_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("startUpdateServerThread",2400,G__viewserverDict_602_0_32, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("stopServerThread",1685,G__viewserverDict_602_0_33, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("sigFinishedReg",1419,G__viewserverDict_602_0_34, 121, -1, -1, 0, 0, 1, 1, 0, "", "*SIGNAL*", (void*) NULL, 0);
   G__memfunc_setup("sigSetCanData",1275,G__viewserverDict_602_0_35, 121, -1, -1, 0, 0, 1, 1, 0, "", "*SIGNAL*", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__viewserverDict_602_0_36, 85, G__get_linked_tagnum(&G__viewserverDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&viewServer::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__viewserverDict_602_0_37, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&viewServer::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__viewserverDict_602_0_38, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&viewServer::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__viewserverDict_602_0_39, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&viewServer::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__viewserverDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__viewserverDict_602_0_43, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__viewserverDict_602_0_44, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&viewServer::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__viewserverDict_602_0_45, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&viewServer::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__viewserverDict_602_0_46, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&viewServer::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__viewserverDict_602_0_47, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&viewServer::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~viewServer", 1200, G__viewserverDict_602_0_48, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncviewserverDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalviewserverDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcviewserverDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__viewserverDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TSocket = { "TSocket" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TServerSocket = { "TServerSocket" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TMessage = { "TMessage" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TThread = { "TThread" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TMonitor = { "TMonitor" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TH2 = { "TH2" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TH3 = { "TH3" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__viewserverDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TSQLStatement = { "TSQLStatement" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_TSQLServer = { "TSQLServer" , 99 , -1 };
G__linked_taginfo G__viewserverDictLN_viewServer = { "viewServer" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableviewserverDict() {
  G__viewserverDictLN_TClass.tagnum = -1 ;
  G__viewserverDictLN_TBuffer.tagnum = -1 ;
  G__viewserverDictLN_TMemberInspector.tagnum = -1 ;
  G__viewserverDictLN_TString.tagnum = -1 ;
  G__viewserverDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__viewserverDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__viewserverDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__viewserverDictLN_TList.tagnum = -1 ;
  G__viewserverDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__viewserverDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__viewserverDictLN_TSocket.tagnum = -1 ;
  G__viewserverDictLN_TServerSocket.tagnum = -1 ;
  G__viewserverDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__viewserverDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__viewserverDictLN_TMessage.tagnum = -1 ;
  G__viewserverDictLN_TThread.tagnum = -1 ;
  G__viewserverDictLN_TQObject.tagnum = -1 ;
  G__viewserverDictLN_TQObjSender.tagnum = -1 ;
  G__viewserverDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__viewserverDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__viewserverDictLN_TMonitor.tagnum = -1 ;
  G__viewserverDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__viewserverDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__viewserverDictLN_TH1.tagnum = -1 ;
  G__viewserverDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__viewserverDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__viewserverDictLN_TH2.tagnum = -1 ;
  G__viewserverDictLN_TH3.tagnum = -1 ;
  G__viewserverDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__viewserverDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__viewserverDictLN_TSQLStatement.tagnum = -1 ;
  G__viewserverDictLN_TSQLServer.tagnum = -1 ;
  G__viewserverDictLN_viewServer.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableviewserverDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TString);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TList);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TSocket);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TServerSocket);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TMessage);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TThread);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TQObjSender);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TMonitor);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TH1);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TH2);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TH3);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TSQLStatement);
   G__get_linked_tagnum_fwd(&G__viewserverDictLN_TSQLServer);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__viewserverDictLN_viewServer),sizeof(viewServer),-1,262400,(char*)NULL,G__setup_memvarviewServer,G__setup_memfuncviewServer);
}
extern "C" void G__cpp_setupviewserverDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupviewserverDict()");
  G__set_cpp_environmentviewserverDict();
  G__cpp_setup_tagtableviewserverDict();

  G__cpp_setup_inheritanceviewserverDict();

  G__cpp_setup_typetableviewserverDict();

  G__cpp_setup_memvarviewserverDict();

  G__cpp_setup_memfuncviewserverDict();
  G__cpp_setup_globalviewserverDict();
  G__cpp_setup_funcviewserverDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncviewserverDict();
  return;
}
class G__cpp_setup_initviewserverDict {
  public:
    G__cpp_setup_initviewserverDict() { G__add_setup_func("viewserverDict",(G__incsetup)(&G__cpp_setupviewserverDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initviewserverDict() { G__remove_setup_func("viewserverDict"); }
};
G__cpp_setup_initviewserverDict G__cpp_setup_initializerviewserverDict;

